//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 13.1.2017 22:36:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace Db201617zVaProektRnabContext
{

    /// <summary>
    /// There are no comments for Db201617zVaProektRnabContext.AviokompanijaSoNajgolemProfit in the schema.
    /// </summary>
    [Table(Name = @"public.aviokompanija_so_najgolem_profit")]
    public partial class AviokompanijaSoNajgolemProfit
    {
        #pragma warning disable 0649

        private string _Aviokompanija;

        private System.Nullable<float> _Profit;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnLoaded method in the schema.
        /// </summary>
        partial void OnLoaded();

        /// <summary>
        /// There are no comments for OnValidate method in the schema.
        /// </summary>
        partial void OnValidate(ChangeAction action);

        /// <summary>
        /// There are no comments for OnCreated method in the schema.
        /// </summary>
        partial void OnCreated();

        /// <summary>
        /// There are no comments for OnAviokompanijaChanging method in the schema.
        /// </summary>
        partial void OnAviokompanijaChanging(string value);

        /// <summary>
        /// There are no comments for OnAviokompanijaChanged method in the schema.
        /// </summary>
        partial void OnAviokompanijaChanged();

        /// <summary>
        /// There are no comments for OnProfitChanging method in the schema.
        /// </summary>
        partial void OnProfitChanging(System.Nullable<float> value);

        /// <summary>
        /// There are no comments for OnProfitChanged method in the schema.
        /// </summary>
        partial void OnProfitChanged();
        #endregion

        /// <summary>
        /// There are no comments for AviokompanijaSoNajgolemProfit constructor in the schema.
        /// </summary>
        public AviokompanijaSoNajgolemProfit()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Aviokompanija in the schema.
        /// </summary>
        [Column(Name = @"aviokompanija", Storage = "_Aviokompanija", DbType = "VARCHAR(100)", UpdateCheck = UpdateCheck.Never)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public string Aviokompanija
        {
            get
            {
                return this._Aviokompanija;
            }
            set
            {
                if (this._Aviokompanija != value)
                {
                    this._Aviokompanija = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Profit in the schema.
        /// </summary>
        [Column(Name = @"profit", Storage = "_Profit", DbType = "FLOAT4", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<float> Profit
        {
            get
            {
                return this._Profit;
            }
            set
            {
                if (this._Profit != value)
                {
                    this._Profit = value;
                }
            }
        }
    }

}
