//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 2/5/2017 12:35:36 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace Db201617zVaProektRnabContext
{

    /// <summary>
    /// There are no comments for Db201617zVaProektRnabContext.Denovi in the schema.
    /// </summary>
    [Table(Name = @"public.denovi")]
    public partial class Denovi : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _DenId;

        private short _RedenBroj;

        private string _ImeNaDen;
        #pragma warning restore 0649

        private EntitySet<Rasporedi> _Rasporedis_DenNaPoletuvanje;

        private EntitySet<Rasporedi> _Rasporedis_DenNaSletuvanje;

        private EntitySet<DenoviNaLetanje> _DenoviNaLetanjes_DenId;
    
        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnLoaded method in the schema.
        /// </summary>
        partial void OnLoaded();

        /// <summary>
        /// There are no comments for OnValidate method in the schema.
        /// </summary>
        partial void OnValidate(ChangeAction action);

        /// <summary>
        /// There are no comments for OnCreated method in the schema.
        /// </summary>
        partial void OnCreated();

        /// <summary>
        /// There are no comments for OnDenIdChanging method in the schema.
        /// </summary>
        partial void OnDenIdChanging(int value);

        /// <summary>
        /// There are no comments for OnDenIdChanged method in the schema.
        /// </summary>
        partial void OnDenIdChanged();

        /// <summary>
        /// There are no comments for OnRedenBrojChanging method in the schema.
        /// </summary>
        partial void OnRedenBrojChanging(short value);

        /// <summary>
        /// There are no comments for OnRedenBrojChanged method in the schema.
        /// </summary>
        partial void OnRedenBrojChanged();

        /// <summary>
        /// There are no comments for OnImeNaDenChanging method in the schema.
        /// </summary>
        partial void OnImeNaDenChanging(string value);

        /// <summary>
        /// There are no comments for OnImeNaDenChanged method in the schema.
        /// </summary>
        partial void OnImeNaDenChanged();
        #endregion

        /// <summary>
        /// There are no comments for Denovi constructor in the schema.
        /// </summary>
        public Denovi()
        {
            this._Rasporedis_DenNaPoletuvanje = new EntitySet<Rasporedi>(new Action<Rasporedi>(this.attach_Rasporedis_DenNaPoletuvanje), new Action<Rasporedi>(this.detach_Rasporedis_DenNaPoletuvanje));
            this._Rasporedis_DenNaSletuvanje = new EntitySet<Rasporedi>(new Action<Rasporedi>(this.attach_Rasporedis_DenNaSletuvanje), new Action<Rasporedi>(this.detach_Rasporedis_DenNaSletuvanje));
            this._DenoviNaLetanjes_DenId = new EntitySet<DenoviNaLetanje>(new Action<DenoviNaLetanje>(this.attach_DenoviNaLetanjes_DenId), new Action<DenoviNaLetanje>(this.detach_DenoviNaLetanjes_DenId));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for DenId in the schema.
        /// </summary>
        [Column(Name = @"den_id", Storage = "_DenId", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "SERIAL NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public int DenId
        {
            get
            {
                return this._DenId;
            }
            set
            {
                if (this._DenId != value)
                {
                    this.OnDenIdChanging(value);
                    this.SendPropertyChanging();
                    this._DenId = value;
                    this.SendPropertyChanged("DenId");
                    this.OnDenIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for RedenBroj in the schema.
        /// </summary>
        [Column(Name = @"reden_broj", Storage = "_RedenBroj", CanBeNull = false, DbType = "INT2 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        [System.ComponentModel.DataAnnotations.Required()]
        public short RedenBroj
        {
            get
            {
                return this._RedenBroj;
            }
            set
            {
                if (this._RedenBroj != value)
                {
                    this.OnRedenBrojChanging(value);
                    this.SendPropertyChanging();
                    this._RedenBroj = value;
                    this.SendPropertyChanged("RedenBroj");
                    this.OnRedenBrojChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ImeNaDen in the schema.
        /// </summary>
        [Column(Name = @"ime_na_den", Storage = "_ImeNaDen", CanBeNull = false, DbType = "VARCHAR(100) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string ImeNaDen
        {
            get
            {
                return this._ImeNaDen;
            }
            set
            {
                if (this._ImeNaDen != value)
                {
                    this.OnImeNaDenChanging(value);
                    this.SendPropertyChanging();
                    this._ImeNaDen = value;
                    this.SendPropertyChanged("ImeNaDen");
                    this.OnImeNaDenChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Rasporedis_DenNaPoletuvanje in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Denovi_Rasporedi", Storage="_Rasporedis_DenNaPoletuvanje", ThisKey="DenId", OtherKey="DenNaPoletuvanje", DeleteRule="NO ACTION")]
        public EntitySet<Rasporedi> Rasporedis_DenNaPoletuvanje
        {
            get
            {
                return this._Rasporedis_DenNaPoletuvanje;
            }
            set
            {
                this._Rasporedis_DenNaPoletuvanje.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Rasporedis_DenNaSletuvanje in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Denovi_Rasporedi1", Storage="_Rasporedis_DenNaSletuvanje", ThisKey="DenId", OtherKey="DenNaSletuvanje", DeleteRule="NO ACTION")]
        public EntitySet<Rasporedi> Rasporedis_DenNaSletuvanje
        {
            get
            {
                return this._Rasporedis_DenNaSletuvanje;
            }
            set
            {
                this._Rasporedis_DenNaSletuvanje.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for DenoviNaLetanjes_DenId in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Denovi_DenoviNaLetanje", Storage="_DenoviNaLetanjes_DenId", ThisKey="DenId", OtherKey="DenId", DeleteRule="NO ACTION")]
        public EntitySet<DenoviNaLetanje> DenoviNaLetanjes_DenId
        {
            get
            {
                return this._DenoviNaLetanjes_DenId;
            }
            set
            {
                this._DenoviNaLetanjes_DenId.Assign(value);
            }
        }
   
        /// <summary>
        /// There are no comments for PropertyChanging event in the schema.
        /// </summary>
        public event PropertyChangingEventHandler PropertyChanging;

        /// <summary>
        /// There are no comments for PropertyChanged event in the schema.
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// There are no comments for SendPropertyChanging method in the schema.
        /// </summary>
        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        /// <summary>
        /// There are no comments for SendPropertyChanging method in the schema.
        /// </summary>
        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        /// <summary>
        /// There are no comments for SendPropertyChanged method in the schema.
        /// </summary>
        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Rasporedis_DenNaPoletuvanje(Rasporedi entity)
        {
            this.SendPropertyChanging("Rasporedis_DenNaPoletuvanje");
            entity.Denovi_DenNaPoletuvanje = this;
        }
    
        private void detach_Rasporedis_DenNaPoletuvanje(Rasporedi entity)
        {
            this.SendPropertyChanging("Rasporedis_DenNaPoletuvanje");
            entity.Denovi_DenNaPoletuvanje = null;
        }

        private void attach_Rasporedis_DenNaSletuvanje(Rasporedi entity)
        {
            this.SendPropertyChanging("Rasporedis_DenNaSletuvanje");
            entity.Denovi_DenNaSletuvanje = this;
        }
    
        private void detach_Rasporedis_DenNaSletuvanje(Rasporedi entity)
        {
            this.SendPropertyChanging("Rasporedis_DenNaSletuvanje");
            entity.Denovi_DenNaSletuvanje = null;
        }

        private void attach_DenoviNaLetanjes_DenId(DenoviNaLetanje entity)
        {
            this.SendPropertyChanging("DenoviNaLetanjes_DenId");
            entity.Denovi_DenId = this;
        }
    
        private void detach_DenoviNaLetanjes_DenId(DenoviNaLetanje entity)
        {
            this.SendPropertyChanging("DenoviNaLetanjes_DenId");
            entity.Denovi_DenId = null;
        }
    }

}
