//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 13.1.2017 22:36:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace Db201617zVaProektRnabContext
{

    /// <summary>
    /// There are no comments for Db201617zVaProektRnabContext.DrzhaviSoNajvekePatuvanja in the schema.
    /// </summary>
    [Table(Name = @"public.drzhavi_so_najveke_patuvanja")]
    public partial class DrzhaviSoNajvekePatuvanja
    {
        #pragma warning disable 0649

        private System.Nullable<int> _Komp;

        private string _Drzhava;

        private System.Nullable<long> _Broj;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnLoaded method in the schema.
        /// </summary>
        partial void OnLoaded();

        /// <summary>
        /// There are no comments for OnValidate method in the schema.
        /// </summary>
        partial void OnValidate(ChangeAction action);

        /// <summary>
        /// There are no comments for OnCreated method in the schema.
        /// </summary>
        partial void OnCreated();

        /// <summary>
        /// There are no comments for OnKompChanging method in the schema.
        /// </summary>
        partial void OnKompChanging(System.Nullable<int> value);

        /// <summary>
        /// There are no comments for OnKompChanged method in the schema.
        /// </summary>
        partial void OnKompChanged();

        /// <summary>
        /// There are no comments for OnDrzhavaChanging method in the schema.
        /// </summary>
        partial void OnDrzhavaChanging(string value);

        /// <summary>
        /// There are no comments for OnDrzhavaChanged method in the schema.
        /// </summary>
        partial void OnDrzhavaChanged();

        /// <summary>
        /// There are no comments for OnBrojChanging method in the schema.
        /// </summary>
        partial void OnBrojChanging(System.Nullable<long> value);

        /// <summary>
        /// There are no comments for OnBrojChanged method in the schema.
        /// </summary>
        partial void OnBrojChanged();
        #endregion

        /// <summary>
        /// There are no comments for DrzhaviSoNajvekePatuvanja constructor in the schema.
        /// </summary>
        public DrzhaviSoNajvekePatuvanja()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Komp in the schema.
        /// </summary>
        [Column(Name = @"komp", Storage = "_Komp", DbType = "INT4", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> Komp
        {
            get
            {
                return this._Komp;
            }
            set
            {
                if (this._Komp != value)
                {
                    this._Komp = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Drzhava in the schema.
        /// </summary>
        [Column(Name = @"drzhava", Storage = "_Drzhava", CanBeNull = false, DbType = "VARCHAR(255) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string Drzhava
        {
            get
            {
                return this._Drzhava;
            }
            set
            {
                if (this._Drzhava != value)
                {
                    this._Drzhava = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Broj in the schema.
        /// </summary>
        [Column(Name = @"broj", Storage = "_Broj", DbType = "INT8", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> Broj
        {
            get
            {
                return this._Broj;
            }
            set
            {
                if (this._Broj != value)
                {
                    this._Broj = value;
                }
            }
        }
    }

}
