//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 2/5/2017 12:35:36 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace Db201617zVaProektRnabContext
{

    /// <summary>
    /// There are no comments for Db201617zVaProektRnabContext.Klasi in the schema.
    /// </summary>
    [Table(Name = @"public.klasi")]
    public partial class Klasi : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _KlasaId;

        private int _TipId;

        private string _ImeNaKlasa;

        private int _BrojNaSedistaVoKlasa;
        #pragma warning restore 0649

        private EntityRef<TipNaAvioni> _TipNaAvioni_TipId;

        private EntitySet<Sedishta> _Sedishtas_KlasaId;

        private EntitySet<Cenovnici> _Cenovnicis_KlasaId;
    
        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnLoaded method in the schema.
        /// </summary>
        partial void OnLoaded();

        /// <summary>
        /// There are no comments for OnValidate method in the schema.
        /// </summary>
        partial void OnValidate(ChangeAction action);

        /// <summary>
        /// There are no comments for OnCreated method in the schema.
        /// </summary>
        partial void OnCreated();

        /// <summary>
        /// There are no comments for OnKlasaIdChanging method in the schema.
        /// </summary>
        partial void OnKlasaIdChanging(int value);

        /// <summary>
        /// There are no comments for OnKlasaIdChanged method in the schema.
        /// </summary>
        partial void OnKlasaIdChanged();

        /// <summary>
        /// There are no comments for OnTipIdChanging method in the schema.
        /// </summary>
        partial void OnTipIdChanging(int value);

        /// <summary>
        /// There are no comments for OnTipIdChanged method in the schema.
        /// </summary>
        partial void OnTipIdChanged();

        /// <summary>
        /// There are no comments for OnImeNaKlasaChanging method in the schema.
        /// </summary>
        partial void OnImeNaKlasaChanging(string value);

        /// <summary>
        /// There are no comments for OnImeNaKlasaChanged method in the schema.
        /// </summary>
        partial void OnImeNaKlasaChanged();

        /// <summary>
        /// There are no comments for OnBrojNaSedistaVoKlasaChanging method in the schema.
        /// </summary>
        partial void OnBrojNaSedistaVoKlasaChanging(int value);

        /// <summary>
        /// There are no comments for OnBrojNaSedistaVoKlasaChanged method in the schema.
        /// </summary>
        partial void OnBrojNaSedistaVoKlasaChanged();
        #endregion

        /// <summary>
        /// There are no comments for Klasi constructor in the schema.
        /// </summary>
        public Klasi()
        {
            this._TipNaAvioni_TipId  = default(EntityRef<TipNaAvioni>);
            this._Sedishtas_KlasaId = new EntitySet<Sedishta>(new Action<Sedishta>(this.attach_Sedishtas_KlasaId), new Action<Sedishta>(this.detach_Sedishtas_KlasaId));
            this._Cenovnicis_KlasaId = new EntitySet<Cenovnici>(new Action<Cenovnici>(this.attach_Cenovnicis_KlasaId), new Action<Cenovnici>(this.detach_Cenovnicis_KlasaId));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for KlasaId in the schema.
        /// </summary>
        [Column(Name = @"klasa_id", Storage = "_KlasaId", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "SERIAL NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public int KlasaId
        {
            get
            {
                return this._KlasaId;
            }
            set
            {
                if (this._KlasaId != value)
                {
                    this.OnKlasaIdChanging(value);
                    this.SendPropertyChanging();
                    this._KlasaId = value;
                    this.SendPropertyChanged("KlasaId");
                    this.OnKlasaIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TipId in the schema.
        /// </summary>
        [Column(Name = @"tip_id", Storage = "_TipId", CanBeNull = false, DbType = "INT4 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        [System.ComponentModel.DataAnnotations.Required()]
        public int TipId
        {
            get
            {
                return this._TipId;
            }
            set
            {
                if (this._TipId != value)
                {
                    if (this._TipNaAvioni_TipId.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnTipIdChanging(value);
                    this.SendPropertyChanging();
                    this._TipId = value;
                    this.SendPropertyChanged("TipId");
                    this.OnTipIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ImeNaKlasa in the schema.
        /// </summary>
        [Column(Name = @"ime_na_klasa", Storage = "_ImeNaKlasa", CanBeNull = false, DbType = "VARCHAR(100) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        [System.ComponentModel.DataAnnotations.StringLength(100)]
        [System.ComponentModel.DataAnnotations.Required()]
        public string ImeNaKlasa
        {
            get
            {
                return this._ImeNaKlasa;
            }
            set
            {
                if (this._ImeNaKlasa != value)
                {
                    this.OnImeNaKlasaChanging(value);
                    this.SendPropertyChanging();
                    this._ImeNaKlasa = value;
                    this.SendPropertyChanged("ImeNaKlasa");
                    this.OnImeNaKlasaChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BrojNaSedistaVoKlasa in the schema.
        /// </summary>
        [Column(Name = @"broj_na_sedista_vo_klasa", Storage = "_BrojNaSedistaVoKlasa", CanBeNull = false, DbType = "INT4 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        [System.ComponentModel.DataAnnotations.Required()]
        public int BrojNaSedistaVoKlasa
        {
            get
            {
                return this._BrojNaSedistaVoKlasa;
            }
            set
            {
                if (this._BrojNaSedistaVoKlasa != value)
                {
                    this.OnBrojNaSedistaVoKlasaChanging(value);
                    this.SendPropertyChanging();
                    this._BrojNaSedistaVoKlasa = value;
                    this.SendPropertyChanged("BrojNaSedistaVoKlasa");
                    this.OnBrojNaSedistaVoKlasaChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TipNaAvioni_TipId in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="TipNaAvioni_Klasi", Storage="_TipNaAvioni_TipId", ThisKey="TipId", OtherKey="TipId", IsForeignKey=true, DeleteOnNull=true)]
        public TipNaAvioni TipNaAvioni_TipId
        {
            get
            {
                return this._TipNaAvioni_TipId.Entity;
            }
            set
            {
                TipNaAvioni previousValue = this._TipNaAvioni_TipId.Entity;
                if ((previousValue != value) || (this._TipNaAvioni_TipId.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._TipNaAvioni_TipId.Entity = null;
                        previousValue.Klasis_TipId.Remove(this);
                    }
                    this._TipNaAvioni_TipId.Entity = value;
                    if (value != null)
                    {
                        this._TipId = value.TipId;
                        value.Klasis_TipId.Add(this);
                    }
                    else
                    {
                        this._TipId = default(int);
                    }
                    this.SendPropertyChanged("TipNaAvioni_TipId");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Sedishtas_KlasaId in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Klasi_Sedishta", Storage="_Sedishtas_KlasaId", ThisKey="KlasaId", OtherKey="KlasaId", DeleteRule="NO ACTION")]
        public EntitySet<Sedishta> Sedishtas_KlasaId
        {
            get
            {
                return this._Sedishtas_KlasaId;
            }
            set
            {
                this._Sedishtas_KlasaId.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Cenovnicis_KlasaId in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Klasi_Cenovnici", Storage="_Cenovnicis_KlasaId", ThisKey="KlasaId", OtherKey="KlasaId", DeleteRule="NO ACTION")]
        public EntitySet<Cenovnici> Cenovnicis_KlasaId
        {
            get
            {
                return this._Cenovnicis_KlasaId;
            }
            set
            {
                this._Cenovnicis_KlasaId.Assign(value);
            }
        }
   
        /// <summary>
        /// There are no comments for PropertyChanging event in the schema.
        /// </summary>
        public event PropertyChangingEventHandler PropertyChanging;

        /// <summary>
        /// There are no comments for PropertyChanged event in the schema.
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// There are no comments for SendPropertyChanging method in the schema.
        /// </summary>
        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        /// <summary>
        /// There are no comments for SendPropertyChanging method in the schema.
        /// </summary>
        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        /// <summary>
        /// There are no comments for SendPropertyChanged method in the schema.
        /// </summary>
        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Sedishtas_KlasaId(Sedishta entity)
        {
            this.SendPropertyChanging("Sedishtas_KlasaId");
            entity.Klasi_KlasaId = this;
        }
    
        private void detach_Sedishtas_KlasaId(Sedishta entity)
        {
            this.SendPropertyChanging("Sedishtas_KlasaId");
            entity.Klasi_KlasaId = null;
        }

        private void attach_Cenovnicis_KlasaId(Cenovnici entity)
        {
            this.SendPropertyChanging("Cenovnicis_KlasaId");
            entity.Klasi_KlasaId = this;
        }
    
        private void detach_Cenovnicis_KlasaId(Cenovnici entity)
        {
            this.SendPropertyChanging("Cenovnicis_KlasaId");
            entity.Klasi_KlasaId = null;
        }
    }

}
